### ISSUE TITLE
warning new version

### ISSUE THREAD

**Issue by gabrielverani** [HomeACcessoryKid/life-cycle-manager#13]
Hello, is it possible that I have a feature with a warning that you have a new version?

**Comment by HomeACcessoryKid** [comment]
Yes, github has a follow feature, just sign up. 

BR,
HacK

**Comment by HomeACcessoryKid** [comment]
Actually I realise it is called "Watch" and it offer the option 'releases only' which is closest to what you a asked for.
But please realise that with the complexity that LCM has in it to provide backward comaptibilty for the already 12000 unique devices out there, it is hard for me to deliver a new version. So, it is good to use that feature, but don't expect it to upgrade soon.

Another question is, what would you hope it would improve that would make a difference?

Thanks for your interest,
HacK

**Comment by HomeACcessoryKid** [comment]
you would like to know that I have started to create new versions but in a parallel repo called [LCMdev](https://github.com/HomeACcessoryKid/LCMdev)
