### ISSUE TITLE
Question: Customize UI and code

### ISSUE THREAD

**Issue by HomeKidd** [HomeACcessoryKid/life-cycle-manager#15]
Hi!
Is it possible to customize the code both for UI and default repo (and LCM- wifi  AP name etc)?
It will look for newer LCM version of your code or what i'm compiled?
Basic idea is to simplify the LCM setup on first startup for users to skip the repo name and .bin name setup for easier use 😄
~~Also i've custom UI for _esp-wifi-config_ and i want to implement it too~~ Its done  😄

Are you planning to make a version with better customization? Like one `#define` for repo name and for .bin, and for the wifi-config (LCM-), so everybody who want to implement OTA can define the default variables and the (end)user only have to Join wifi network without adding any variables - correctly - on first startup 😄 
Other question is, is it possible to change the flash size to 32 for 4mb flash devices?

**Comment by HomeACcessoryKid** [comment]
I would suggest that your setup process then after erasing the flash, it flashes a pre-populated sysconfig sector with the relevant values. In that case you have achieved what you want…
Defining those sectors I leave to you. Just look for the various references to sysconfig in my code and you will see what to put where.

Hope this helps

I could give you write access to the Wiki pages to create instructions for this...
