### ISSUE TITLE
Question: Going from LCM to other firmwares?

### ISSUE THREAD

**Issue by peros550** [HomeACcessoryKid/life-cycle-manager#26]
It would be very helpful to know if it is possible to load a different firmware (ie Tasmota / EspHome) and go away from LCM. 

This function may be needed from someone who would like to explore different firmwares on devices where wire flashing is very difficult (ie bulbs)

**Comment by HomeACcessoryKid** [comment]
This would mean considerable rework on the LCM logic.
So the answer is no.

But bulbs are cheap, so why not buy two?

**Comment by peros550** [comment]
Thank you for your feedback. 

Yeap it's not a matter of cost, rather than an inconvenience when you switch to a firmware and feel this is not quite right yet when it comes to bulb support, color , white temperature reproduction.

Hence, instead of just switching to another firmware, you need to wait a few weeks for a new bulbs to arrive. 

I do understand that rework on the LCM logic is huge, so thank you once again for your work! All the best!
