### ISSUE TITLE
Replace LCM with HAA_OTA

### ISSUE THREAD

**Issue by peros550** [HomeACcessoryKid/life-cycle-manager#27]
Hi @HomeACcessoryKid 

I'm, wondering if there is a way to replace LCM with HAA_OTA. As you may be aware of, future versions of HAA require the HAA_OTA boot instead of LCM due to size constraints. 

Are you aware of any OTA method to replace LCM with HAA_OTA?

**Comment by HomeACcessoryKid** [comment]
Maybe, however be aware that I have introduced rboot4lcm and that might be something that could be in the way. I will look into this after my holidays, so repeat your question so I don’t forget 

BR,
HacK

**Comment by peros550** [comment]
Hi @HomeACcessoryKid are you back from holidays? All good? Just a gentle reminder on this topic.

**Comment by HomeACcessoryKid** [comment]
Yes I am back, thanks. The holiday was good.

How to to replace LCM with HAA_OTA? It would have to happen using the emergency mode which cane accessed by 12 power cycles.
Then it is a matter of taking a HAA_OTA binary and rename it to otaboot.bin AND __ I  __  need to sign that binary as valid.
I am willing to do that for selected binaries, if you provide a clean reference to the official ravensystem distribution.

I  can host them somewhere on GitHub after testing the concept (by you)

**Comment by peros550** [comment]
Thank you for your response! Really sorry to bother you with all this. 

What do you mean by saying a clean reference to official ravensystem distribution? You mean the version of HAA_OTA ?

**Comment by RavenSystem** [comment]
https://github.com/RavenSystem/haa/releases/download/3.5.11/haaboot.bin

**Comment by peros550** [comment]
Hi guys, any news on the above? I'm ready for some tests this weekend :)

**Comment by peros550** [comment]
> Yes I am back, thanks. The holiday was good. How to to replace LCM with HAA_OTA? It would have to happen using the emergency mode which cane accessed by 12 power cycles. Then it is a matter of taking a HAA_OTA binary and rename it to otaboot.bin AND __ I __ need to sign that binary as valid. I am willing to do that for selected binaries, if you provide a clean reference to the official ravensystem distribution. I can host them somewhere on GitHub after testing the concept (by you)

@RavenSystem @HomeACcessoryKid 

Should we make this test and see if it's possible?

**Comment by RavenSystem** [comment]
You can install HAA OTA from LCM setting repo and filename:
Repo: RavenSystem/haa_ota
Filename: haaboot.bin

But remember that LCM uses a custom rboot that has a delay of 1.5s at boot, and in that time, all GPIOs are free and it can cause issues and undesired behaviors like turning on relays and turning on lights, opening locks, garage doors, window coverings...

**Comment by RavenSystem** [comment]
https://github.com/HomeACcessoryKid/life-cycle-manager/issues/29#issuecomment-773194584

**Comment by peros550** [comment]
many thanks!
