### ISSUE TITLE
GitHub provides until 31 March 2021 to update our LCM to a safe version

### ISSUE THREAD

**Issue by HomeACcessoryKid** [HomeACcessoryKid/life-cycle-manager#29]
UPDATE: It so happens that AWS will update their certificate provider on 23 March.  
Please update before this, I will not update the certificate in LCM for that 1 week.
https://forums.aws.amazon.com/ann.jspa?annID=7541

As discussed in #23 GitHub has offered us until 31 March to use the original S3 server.

This issue will provide information about the creation of a new version that will be able to work when the new GitHub owned content delivery network will again be used.

The key obstacle is the use of SNI extension. I will need time to build and TEST that all is in good shape, so for now spread the word and point people to this issue so they stay informed.

I hope to provide new info by the end of this weekend.

**Comment by tonysprenk** [comment]
still getting `wolfSSL_send error = -322 `. any idea?

**Comment by HomeACcessoryKid** [comment]
Just so you all know, the github fix only works for the repo that is LCM itself. But when the current LCM arrives at the part where it will load the user repo, it will use the new server once more. So, unless I submit a new LCM, it means that end-user experience is that it does not work!
So, until I make a new version, you are stuck...

**Comment by HomeACcessoryKid** [comment]
It WORKS already!
When I realised the end user experience was not OK, I decided to act this evening and we have a new version (2.1.2) that WORKS. It even fixes a 1.0.0 or even older(?) LCM device.
Update time is about 6-10 minutes, but keep track with `nc -kulnw0 45678`

Know that I will incorporate an additional feature regarding the wifi gui, so if you want to save yourself a second time 6 minute wait, then wait for maybe one or two weeks... it is up to you

**Comment by RavenSystem** [comment]
I have released a special version of HAA Installer to allow updates from old HAA versions installed with LCM v1.0. 

Remember to save a copy of your JSON before update, because all saved settings will be removed. HomeKit ID is preserved, meaning that accessory and automations will work again once configured. 

rboot4lcm will be replaced with original rboot during update to avoid 1.5s delay at boot.

**Comment by HomeACcessoryKid** [comment]
The switch over to the final (for now, 2021Q1) situation happened somewhere around 31 march.
I am closing this issue since it is all history now.
The Wifi version referred to above did not happen, just so you know.
2.1.2 remains the relevant version for now.
