### ISSUE TITLE
LCM 2.2.6 - Wolf SSL error downloading user app

### ISSUE THREAD

**Issue by Doodles2000** [HomeACcessoryKid/life-cycle-manager#36]
Hi HACK and Team,

Noticed a problem with LCM 226 where it seems to freak out when downloading the user app.  Tried full erase of flash (on several modules).

Thinking it may have been something wrong with my app / signature files. I tested using the default "HomeACcessoryKid/ota-demo" with the same results.

It appears the fault is coming from a  wolfSSL_send error = -188 which then causes the Fatal exception (28)

I'm out of my depth to go any further for a resolution.

Attached is UDPlogger and serial port captures - hopefully these help narrow down the cause.

[20240324-LCM226-udplog.txt](https://github.com/HomeACcessoryKid/life-cycle-manager/files/14734012/20240324-LCM226-udplog.txt)
[20240324-LCM226-serial.txt](https://github.com/HomeACcessoryKid/life-cycle-manager/files/14734039/20240324-LCM226-serial.txt)

**Comment by HomeACcessoryKid** [comment]
Hi, thanks for reporting.
Very first attempt shows error -188 as well.
Guess I'll be debugging today...
Stay tuned

**Comment by HomeACcessoryKid** [comment]
FIXED

Github has updated their certificates so I have created the matching certs.sector and put that in the existing release.
This means there will not be a version update of LCM itself, but you should see a certificate swap.
Please confirm this works for you as well?

TIA,
HacK
```
...
HTTP returns 302 for HomeACcessoryKid/life-cycle-manager@version:"2.2.6" according to latest release
--- ota_boot...1
HomeACcessoryKid/life-cycle-manager@version:"2.2.6"
--- ota_get_hash
--- ota_get_file_ex
GET /HomeACcessoryKid/life-cycle-manager/releases/download/2.2.6/certs.sector.sig HTTP/1.1
Host: github.com

--- ota_connect LocalPort=d0ab DNS IP:140.82.121.4 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
sent OK
HTTP returns 302
--- ota_connect LocalPort=d0ac DNS IP:185.199.109.133 local..OK remote..OK SSL..OK set_fd to objects.githubusercontent.com port 443..OK
send request......OK
eb1e88...244000  so far collected 156 bytes
--- ota_verify_hash
--- ota_hash
--- ota_hash
--- ota_verify_signature
signature valid: 1
--- ota_get_file
--- ota_get_file_ex
GET /HomeACcessoryKid/life-cycle-manager/releases/download/2.2.6/certs.sector HTTP/1.1
Host: github.com

--- ota_connect LocalPort=d0ad DNS IP:140.82.121.4 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
sent OK
HTTP returns 302
--- ota_connect LocalPort=d0ae DNS IP:185.199.109.133 local..OK remote..OK SSL..OK set_fd to objects.githubusercontent.com port 443..OK
send request......OK
erasing@0xf9000>307630...446759 445652...533564 496132...464251 39526e...6c7755 484248...ffffff ffffff...ffffff  so far collected 4096 bytes
--- ota_verify_hash
--- ota_hash
--- ota_swap_cert_sector
--- ota_kill_file
--- ota_finalize_file
--- ota_get_pubkey
 04 94 30 cc 5c 4e 50 29 15 ff 3d 41 da e9 e5 e3 64 27 b3 96 07 61 36 a4 83 28 4d fd f9 05 4f 0d 82 fa 57 26 06 b7 e8 1f 22 2d 2b 8a d2 ff 6e ac 59 73 00 b5 e4 9c 5f 68 ab 31 d3 9f ad bb 3d c8 4f 6d 38 e6 6f b8 b3 f7 22 21 b7 f2 e4 b7 75 ed 09 2c 87 2b 00 56 5b 81 e8 64 5c 2c 84 85 c0 3c 34
ret: 0
--- ota_boot...1
--- running ota-main software
...
```

**Comment by Doodles2000** [comment]
Thanks Hack,

Confirming all working well

`>>> wifi_config: wifi_config_server_on_settings_update: Update settings, body = ssid=mkp&password=xxx&led_pin=2&led_pol=0&led_pol=1&otastr=&otarepo=Doodles2000%2Fled-strip-animation-233&otafile=main.bin&otabeta=0
>>> wifi_config: Found configuration, connecting to mkp
station: a0:52:72:1f:7f:95 leave, AID = 1
rm match
bcn 0
del if1
mode : sta(68:c6:3a:c6:17:dd)
Function called without core lock
scandone
reconnect
rm match
scandone
>>> wifi_config: http_task: lwip_read: -1
>>> wifi_config: Client disconnected
add 0
aid 3
cnt 

connected with mkp, channel 3
dhcp client start...
ip:192.168.10.89,mask:255.255.255.0,gw:192.168.10.254
>>> wifi_config: wifi_config_sta_connect_timeout_callback: Successfully connected
>>> wifi_config: Stopping HTTP server
Timer Start Failed
>>> wifi_config: Stopping DNS server
--- on_wifi_ready
--- ota_emergency?
--- ota_init
userbeta='0' otabeta='0'
rboot_config.unused[1]=LEDinfo from 0x52 to 0x52
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
--- led_blink_task blinking led pin 2
--- ota_active_sector: 0xf9000
--- ota_set_verify...OFF
--- DNS: done!
--- ota_get_pubkey
 04 94 30 cc 5c 4e 50 29 15 ff 3d 41 da e9 e5 e3 64 27 b3 96 07 61 36 a4 83 28 4d fd f9 05 4f 0d 82 fa 57 26 06 b7 e8 1f 22 2d 2b 8a d2 ff 6e ac 59 73 00 b5 e4 9c 5f 68 ab 31 d3 9f ad bb 3d c8 4f 6d 38 e6 6f b8 b3 f7 22 21 b7 f2 e4 b7 75 ed 09 2c 87 2b 00 56 5b 81 e8 64 5c 2c 84 85 c0 3c 34
ret: 0
--- ota_get_btl_version
bootloader version:"1.0.1"
--- ota_boot...1
--- ota_load_user_app
user_repo='Doodles2000/led-strip-animation-233' user_version='0.0.0' user_file='main.bin'
--- entering the loop
--- ota_get_pubkey
 04 94 30 cc 5c 4e 50 29 15 ff 3d 41 da e9 e5 e3 64 27 b3 96 07 61 36 a4 83 28 4d fd f9 05 4f 0d 82 fa 57 26 06 b7 e8 1f 22 2d 2b 8a d2 ff 6e ac 59 73 00 b5 e4 9c 5f 68 ab 31 d3 9f ad bb 3d c8 4f 6d 38 e6 6f b8 b3 f7 22 21 b7 f2 e4 b7 75 ed 09 2c 87 2b 00 56 5b 81 e8 64 5c 2c 84 85 c0 3c 34
ret: 0
--- ota_set_verify...OFF
--- ota_get_version
--- ota_connect LocalPort=e4e9 DNS IP:20.248.137.48 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
GET /HomeACcessoryKid/life-cycle-manager/releases/latest HTTP/1.1
Host: github.com

sent OK
HTTP returns 302 for HomeACcessoryKid/life-cycle-manager@version:"2.2.6" according to latest release
--- ota_boot...1
HomeACcessoryKid/life-cycle-manager@version:"2.2.6"
--- ota_get_hash
--- ota_get_file_ex
GET /HomeACcessoryKid/life-cycle-manager/releases/download/2.2.6/certs.sector.sig HTTP/1.1
Host: github.com

--- ota_connect LocalPort=e4ea DNS IP:20.248.137.48 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
sent OK
HTTP returns 302
--- ota_connect LocalPort=e4eb DNS IP:185.199.109.133 local..OK remote..OK SSL..OK set_fd to objects.githubusercontent.com port 443..OK
send request......OK
eb1e88...244000  so far collected 156 bytes
--- ota_verify_hash
--- ota_hash
--- ota_boot...1
--- running ota-main software
--- ota_get_version
--- ota_connect LocalPort=e4ec DNS IP:20.248.137.48 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
GET /HomeACcessoryKid/rboot4lcm/releases/latest HTTP/1.1
Host: github.com

sent OK
HTTP returns 302 for HomeACcessoryKid/rboot4lcm@version:"1.0.1" according to latest release
--- ota_boot...1
HomeACcessoryKid/rboot4lcm@version:"1.0.1"
--- ota_compare 
1.0.1 with 1.0.1=0
--- ota_compare 
2.2.6 with 2.2.6=0
--- ota_set_verify...ON
certs size: 2811
TIME: Mon Mar 25 10:37:40 2024
--- ota_get_version
--- ota_connect LocalPort=e4ed DNS IP:20.248.137.48 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
GET /Doodles2000/led-strip-animation-233/releases/latest HTTP/1.1
Host: github.com

sent OK
HTTP returns 302 for Doodles2000/led-strip-animation-233@version:"0.0.1" according to latest release
--- ota_boot...1
Doodles2000/led-strip-animation-233@version:"0.0.1"
--- ota_compare 
0-0,0.1-0.0
0-0,1-0
1-0
0.0.1 with 0.0.0=1
user_repo='Doodles2000/led-strip-animation-233' new_version='0.0.1' user_file='main.bin'
--- ota_get_hash
--- ota_get_file_ex
GET /Doodles2000/led-strip-animation-233/releases/download/0.0.1/main.bin.sig HTTP/1.1
Host: github.com

--- ota_connect LocalPort=e4ee DNS IP:20.248.137.48 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
sent OK
HTTP returns 302
--- ota_connect LocalPort=e4ef DNS IP:185.199.109.133 local..OK remote..OK SSL..OK set_fd to objects.githubusercontent.com port 443..OK
send request......OK
fdcfdc...072774  so far collected 52 bytes
--- ota_get_file
--- ota_get_file_ex
GET /Doodles2000/led-strip-animation-233/releases/download/0.0.1/main.bin HTTP/1.1
Host: github.com

--- ota_connect LocalPort=e4f0 DNS IP:20.248.137.48 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
sent OK
HTTP returns 302
--- ota_connect LocalPort=e4f1 DNS IP:185.199.109.133 local..OK remote..OK SSL..OK set_fd to objects.githubusercontent.com port 443..OK
send request......OK
`

**Comment by Doodles2000** [comment]
Thanks Hack, 

Confirming all working well!

[20240325-LCM226-serial.txt](https://github.com/HomeACcessoryKid/life-cycle-manager/files/14742447/20240325-LCM226-serial.txt)
