### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by AchimPieters** [HomeACcessoryKid/life-cycle-manager#9]
Hi there!

Great job on your LCM project. But I have a question. How to compile your code myself?
When I compile I says` #error You must set OTAVERSION=x.y.z of the ota code to match github version tag x.y.z` is missing on line 17 form main.c witch refers to OTA.h line 6?

Could you help me compile your code myself? I would be great full.
Thanks in advance.

**Comment by AchimPieters** [comment]
Here's the whole error description:
CC /home/achim/life-cycle-manager/main.c
In file included from /home/achim/life-cycle-manager/main.c:17:0:
./ota.h:6:3: error: #error You must set OTAVERSION=x.y.z of the ota code to match github version tag x.y.z
  #error You must set OTAVERSION=x.y.z of the ota code to match github version tag x.y.z
   ^
In file included from /home/achim/life-cycle-manager/main.c:18:0:
/home/achim/life-cycle-manager/main.c: In function 'ota_task':
/home/achim/life-cycle-manager/main.c:37:28: error: 'OTAVERSION' undeclared (first use in this function)
     UDPLGP("VERSION: %s\n",OTAVERSION); //including the compile time makes comparing binaries impossible, so don't
                            ^
./udplogger.h:9:50: note: in definition of macro 'UDPLGP'
 #define UDPLGP(format, ...)  do {printf(format,##__VA_ARGS__); \
                                                  ^
/home/achim/life-cycle-manager/main.c:37:28: note: each undeclared identifier is reported only once for each function it appears in
     UDPLGP("VERSION: %s\n",OTAVERSION); //including the compile time makes comparing binaries impossible, so don't
                            ^
./udplogger.h:9:50: note: in definition of macro 'UDPLGP'
 #define UDPLGP(format, ...)  do {printf(format,##__VA_ARGS__); \
                                                  ^
make: *** [/home/achim/esp/esp-open-rtos/common.mk:219: build/program//main.o] Error 1

**Comment by AchimPieters** [comment]
never mind found it.

**Comment by haa-systems** [comment]
> never mind found it.

please always place your answer for next people, who can encounter same issue. I saw you just close your own thread twice
